version: "3.9"

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./.volumes/:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_PASS
    
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASS
